# This is a basic workflow to help you get started with Actions

name: First_Workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello, world!"
      - name: Print Goodbye
        run: echo "Done - bye!"
